apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vote-queue
  namespace: survey-app
spec:
  serviceName: vote-queue
  replicas: 1
  selector:
    matchLabels:
      app: vote-queue
  template:
    metadata:
      labels:
        app: vote-queue
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 10
          periodSeconds: 5 