apiVersion: v1
kind: Service
metadata:
  name: vote-queue
  namespace: survey-app
spec:
  selector:
    app: vote-queue
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
  - port: 15672
    targetPort: 15672
    name: management 