apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveys
  namespace: survey-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: surveys
  template:
    metadata:
      labels:
        app: surveys
    spec:
      containers:
      - name: surveys
        image: ${REGISTRY_URL}/survey-service:latest
        env:
        - name: MONGO_URL
          value: "mongodb://survey-storage:27017"
        ports:
        - containerPort: 8081
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5 