apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: survey-storage
  namespace: survey-app
spec:
  serviceName: survey-storage
  replicas: 1
  selector:
    matchLabels:
      app: survey-storage
  template:
    metadata:
      labels:
        app: survey-storage
    spec:
      containers:
      - name: mongo
        image: mongo:4.4
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          exec:
            command:
              - mongo
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - mongo
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-data 