apiVersion: apps/v1
kind: Deployment
metadata:
  name: votes
  namespace: survey-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: votes
  template:
    metadata:
      labels:
        app: votes
    spec:
      containers:
      - name: votes
        image: ${REGISTRY_URL}/vote-service:latest
        env:
        - name: SURVEY_GRPC_HOSTNAME
          value: "surveys"
        - name: RABBITMQ_HOSTNAME
          value: "vote-queue"
        - name: POSTGRES_HOSTNAME
          value: "vote-storage"
        ports:
        - containerPort: 8082
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5 