apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-worker
  namespace: survey-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-worker
  template:
    metadata:
      labels:
        app: vote-worker
    spec:
      containers:
      - name: vote-worker
        image: ${REGISTRY_URL}/vote-worker-service:latest
        env:
        - name: RABBITMQ_HOSTNAME
          value: "vote-queue"
        - name: POSTGRES_HOSTNAME
          value: "vote-storage"
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
          requests:
            memory: "128Mi"
            cpu: "150m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep vote-worker | grep -v grep
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep vote-worker | grep -v grep
          initialDelaySeconds: 5
          periodSeconds: 5 